Algoritmo "idades"

Var

  nome1, nome2: caractere
  idade1, idade2: inteiro
  idadeMedia : real

Inicio

escreval("Dados da primeira pessoa: ")
escreva("Nome: ")
leia(nome1)

escreval

escreva("Idade: ")
leia(idade1)

escreval("Dados da segunda pessoa: ")
escreva("Nome: ")
leia(nome2)

escreval

escreva("Idade: ")
leia(idade2)

 idadeMedia <- (idade1 + idade2) / 2

escreval("A idade média de: ", nome1, " e ", nome2, " é ", idadeMedia:1:1)


Fimalgoritmo