Algoritmo "retangulo"

Var

 base, altura, area, perimetro, diagonal : real
 
Inicio

escreva("Base do retângulo: ")
leia(base)

escreval

escreva("Altura do retângulo: ")
leia(altura)

escreval

area <- base * altura
perimetro <- 2 (base + altura)
diagonal <- raizQ(Exp(base,2) + Exp(altura,2))

escreval("AREA = ",area:1:4)
escreval("PERÍMETRO = ", perimetro:1:4)
escreval("DIAGONAL = ", diagonal:1:4)



Fimalgoritmo