Algoritmo "Entrada_de_dados"

Var

idade : inteiro
salario1, salario2 : real
nome: caractere

Inicio

escreval("Digite o seu nome")
leia(nome)

escreval("Digite sua idade")
leia(idade)


escreval("Digite quanto você ganhou nos 2 últimos meses")
leia(salario1)
leia(salario2)

escreval("DADOS DIGITADOS: ")
escreval("Nome = ", nome)
escreval("Idade = ", idade)
escreval("Salario 1 = ", salario1:1:2)
escreval("Salário 2 = ", salario2:1:2)





Fimalgoritmo