Algoritmo "medidas"

Var

A, B, C, areaTriangulo, areaQuadrado, areaTrapezio: real

Inicio

escreva("Digite a medida A: ")
leia(A)

escreval

escreva("Digite a medida B: ")
leia(B)

escreva("Digite a mediade C: ")
leia(C)

escreval

areaQuadrado <- Exp(A, 2)
areaTriangulo <-  A * B /2
areaTrapezio <-   (A + B) * C / 2

escrevaL("AREA DO QUADRADO: ",areaQuadrado:1:4)
escrevaL("AREA DO TRIÂNGULO: ",areaTriangulo:1:4)
escreva("AREA DO TRAPÉZIO: ",areaTrapezio:1:4)




Fimalgoritmo